platform :ios, '10.0'

target 'TaiChungWeather' do
  use_frameworks!

  pod 'Ji', '~> 5.0.0'
  pod 'DGElasticPullToRefresh', :git => 'https://github.com/KennethTsang/DGElasticPullToRefresh.git'
  pod 'KRProgressHUD'
  
end
